### PR TITLE
Convert ISO/IEC Directives, Part 1 -- Consolidated ISO Supplement

### PR DESCRIPTION
**Pull request by manuel489**
*As requested in https://github.com/metanorma/mn-samples-iso/issues/55*

This PR contains [part 1](https://www.iso.org/sites/directives/current/consolidated/index.xhtml#_idTextAnchor421) of ISO Directives. This document has quite uncommon structure.

Comments:
* There are two groups of annexes: "ISO/IEC ANNEXES" and "ANNEXES APPLICATION TO ISO ONLY". Which are numbered differently. Also, inside of the last group, there are three additional appendices (Appendix 1, 2 and 3).
* There are text blocks that are given as "advisory notes to standards drafters" named "DRAFTING INSTRUCTIONS".

Capture1

I have enclosed these in example blocks.

* There is (what it seems to be) an ITU Standard (`Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC`) packed inside of a Normative Annex (`Annex I`).

Considering the above comments, perhaps it will be necessary to re-arrange the structure of the converted document (maybe as a collection?). But in any case, the heavy work is done.

Thanks!

### CODE REVIEW

**Comment by opoudjis** [comment]
@manuel489 We have modelled Appendix (as annex of annex), https://www.metanorma.com/author/iso/topics/markup/#annexes-and-appendices. But that doesn't address the other issues you're raising.

**Comment by manuel489** [comment]
> @manuel489 We have modelled Appendix (as annex of annex), https://www.metanorma.com/author/iso/topics/markup/#annexes-and-appendices. But that doesn't address the other issues you're raising.

Ok @opoudjis. I have updated the markup. However, something wrong seems to happen with the appendices: cross-references and section numbering aren't working properly.
I have raised an issue in https://github.com/metanorma/metanorma-iso/issues/444

**Comment by opoudjis** [comment]
metanorma/metanorma-iso#444 fixed.

**Comment by ronaldtse** [comment]
Failure in generating part 2 directives:
https://github.com/metanorma/mn-samples-iso/runs/2378001857?check_suite_focus=true

```
[info]: Compiling /__w/mn-samples-iso/mn-samples-iso/sources/directives/part2/document.adoc ...
1753
/usr/local/bundle/gems/rsec-1.0.0/lib/rsec/parser.rb:19:in `parse!':  (Rsec::SyntaxError)
1754
in source:1 at 2
1755
W//(m cdot K)
1756
  ^
1757
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:114:in `parse'
1758
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:159:in `block in MathML2UnitsML'
1759
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
1760
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
1761
	from /usr/local/bundle/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
1762
	from /usr/local/bundle/gems/asciimath2unitsml-0.3.1/lib/asciimath2unitsml/parse.rb:156:in `MathML2UnitsML'
1763
	from /usr/local/bundle/gems/metanorma-standoc-1.9.0/lib/asciidoctor/standoc/cleanup_maths.rb:117:in `block in mathml_cleanup'
1764
```

Bug filed: https://github.com/plurimath/asciimath2unitsml/issues/27

**Comment by ronaldtse** [comment]
Going to merge this when passing, even though PDF has failures (#73 ).

**Comment by ronaldtse** [comment]
Merging despite Windows failure, that will be tracked in #74 .

**Pull request merged**
