### PR TITLE
Add ISO Rice sample documents (IS and amendment) in French

### PR DESCRIPTION
**Pull request by anermina**
Conversion to .adoc is made. I've noticed some bugs in PDF and DOC outputs and will report them as separate tickets tomorrow.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @anermina ! @opoudjis can you confirm that French clauses, e.g. `.Avant-propos` for Foreword, are recognized?

**Comment by ronaldtse** [comment]
@anermina is this mergeable? Is the content produced correct?

**Comment by anermina** [comment]
@ronaldtse Except from the issues reported in https://github.com/metanorma/metanorma-iso/issues/418, https://github.com/metanorma/metanorma-iso/issues/419 and https://github.com/metanorma/metanorma-iso/issues/417, this renders well and I believe it can be merged.

**Comment by ronaldtse** [comment]
Then let's merge this first. Thanks @anermina !

**Pull request merged**
