### PR TITLE
Clean up site commands

### PR DESCRIPTION
**Pull request by ronaldtse**
Somehow this is crashing. I think this is to do with the updated integration between Metanorma and Fontist.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Failure trace:

```
[info]: Compiling /Users/me/src/mn/mn-samples-iso/sources/amendment/rice-amd.awi.adoc ...
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
[relaton] processor "relaton_calconnect" registered
[relaton] processor "relaton_omg" registered
[relaton] processor "relaton_un" registered
[relaton] processor "relaton_w3c" registered
[relaton] processor "relaton_ieee" registered
[relaton] processor "relaton_iho" registered
[relaton] processor "relaton_bipm" registered
[relaton] processor "relaton_ecma" registered
[relaton] processor "relaton_cie" registered
Style: (XML Line 000072): Foreword may contain requirement: ISO shall not be held responsible for identifying any or all such patent rights
Style: (XML Line 000072): Foreword may contain permission: Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights
Style: (XML Line 000072): Foreword may contain recommendation: In particular the different approval criteria needed for the different types of ISO documents should be noted
Style: (XML Line 000119): possible decimal point: 2.1
Metanorma XML Syntax: (XML Line 000132:201): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000137:138): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000141:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000148:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000152:266): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000156:241): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000160:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000164:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000168:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000200:31): element "clause" incomplete; missing required element "clause"
Metanorma XML Syntax: (XML Line 000207:300): element "clause" incomplete; missing required element "clause"
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma)
Traceback (most recent call last):
	69: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
	68: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
	67: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	66: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	65: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	64: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
	63: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	62: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
	61: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	60: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	59: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	58: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
	57: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
	56: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
	55: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
	54: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `<top (required)>'
	53: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `load'
	52: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/exe/metanorma:20:in `<top (required)>'
	51: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli.rb:67:in `start'
	50: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	49: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	48: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	47: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	46: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	45: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	44: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	43: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	42: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	41: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	40: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	39: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/commands/site.rb:25:in `generate'
	38: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/site_generator.rb:23:in `generate'
	37: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/site_generator.rb:28:in `generate'
	36: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/site_generator.rb:28:in `each'
	35: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	34: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/site_generator.rb:81:in `compile'
	33: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/compiler.rb:35:in `compile'
	32: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/compiler.rb:30:in `compile'
	31: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.7.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	30: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.0/lib/metanorma/compile.rb:29:in `compile'
	29: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.0/lib/metanorma/fontist_utils.rb:88:in `install_fonts'
	28: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.0/lib/metanorma/fontist_utils.rb:28:in `install_fonts_safe'
	27: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.0/lib/metanorma/fontist_utils.rb:59:in `fontist_install'
	26: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:21:in `from_hash'
	25: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:26:in `call'
	24: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:38:in `font_paths'
	23: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:38:in `map'
	22: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:38:in `each'
	21: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
	20: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
	19: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:50:in `style_paths'
	18: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:50:in `flat_map'
	17: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:50:in `each'
	16: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
	15: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/install.rb:16:in `file_paths'
	14: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/manifest/locations.rb:74:in `find_font_with_name'
	13: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_font.rb:44:in `find_styles'
	12: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_font.rb:55:in `find_styles'
	11: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_font.rb:63:in `find_by_index'
	10: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:22:in `find'
	 9: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:37:in `system_index'
	 8: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:41:in `build_system_index'
	 7: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/utils/locking.rb:11:in `lock'
	 6: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:42:in `block in build_system_index'
	 5: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:52:in `do_build_system_index'
	 4: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:82:in `detect_paths'
	 3: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:82:in `flat_map'
	 2: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:82:in `each'
	 1: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:85:in `block in detect_paths'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fontist-1.8.12/lib/fontist/system_index.rb:96:in `detect_fonts': /Users/me/.fontist/fonts/pdf_fonts_config.xml.out (Fontist::Errors::UnknownFontTypeError)
```

**Comment by ronaldtse** [comment]
Wait it's passing here. Strange!

**Comment by ronaldtse** [comment]
No -- the PDFs are all 0 bytes.

**Comment by ronaldtse** [comment]
Here's the mn2pdf crash:

```
java -Xss5m -Xmx1024m -jar /usr/local/bundle/gems/mn2pdf-1.29/lib/../bin/mn2pdf.jar --xml-file "/__w/mn-samples-iso/mn-samples-iso/site/documents/amendment/rice-amd-fr.presentation.xml" --xsl-file "/usr/local/bundle/gems/metanorma-iso-1.8.0/lib/isodoc/iso/iso.amendment.xsl" --pdf-file "/__w/mn-samples-iso/mn-samples-iso/site/documents/amendment/rice-amd-fr.pdf" --font-manifest /tmp/fontist_locations20210413-356-1g33858.yml
426
mn2pdf 
427

428

429

430
Input: XML (/__w/mn-samples-iso/mn-samples-iso/site/documents/amendment/rice-amd-fr.presentation.xml)
431
Input: XSL (/usr/local/bundle/gems/metanorma-iso-1.8.0/lib/isodoc/iso/iso.amendment.xsl)
432
Output: PDF (/__w/mn-samples-iso/mn-samples-iso/site/documents/amendment/rice-amd-fr.pdf)
433

434
[INFO] XSL-FO file preparation...
435
Transforming... java.io.IOException: Can't read /root/.metanorma/fonts/SourceHanSans-Normal.ttc
436
	at java.desktop/java.awt.Font.checkFontFile(Font.java:1244)
437
	at java.desktop/java.awt.Font.createFont(Font.java:1224)
438
	at com.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:682)
439
	at com.metanorma.fop.fontConfig.updateConfig(fontConfig.java:361)
440
	at com.metanorma.fop.fontConfig.getConfig(fontConfig.java:649)
441
	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:267)
442
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:238)
443
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:522)
444
java.io.IOException: Can't read /root/.metanorma/fonts/SourceHanSans-Normal.ttc
445
	at java.desktop/java.awt.Font.checkFontFile(Font.java:1244)
446
	at java.desktop/java.awt.Font.createFont(Font.java:1224)
447
	at com.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:682)
448
	at com.metanorma.fop.fontConfig.updateConfig(fontConfig.java:361)
449
```

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help check what this error is? Thanks.

**Comment by ronaldtse** [comment]
And one important problem here -- PDF generation crashes, but the workflows still pass. We have to fix this.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can you help check what this error is? Thanks.

@ronaldtse Looks like fontist didn't install font 'Source Han Sans Normal', therefore mn2pdf tries to read it from `metanorma` folder, but not `fontist` folder. I would like to check it locally on my Windows machine, but can't. 
```
bundle install
metanorma site generate --agree-to-terms
```
```
Could not find asciidoctor-2.0.13 in any of the sources
Run `bundle install` to install missing gems.
```

```
bundle info asciidoctor
```
```
  * asciidoctor (2.0.13)
        Summary: An implementation of the AsciiDoc text processor and publishing toolchain
        Homepage: https://asciidoctor.org
        Path: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.13
```

`dir /b "C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.13"`:
```
.yardopts
asciidoctor.gemspec
bin
CHANGELOG.adoc
data
lib
LICENSE
man
README-de.adoc
README-fr.adoc
README-jp.adoc
README-zh_CN.adoc
README.adoc
```

What I do wrong and it is possible to run it locally?

**Comment by ronaldtse** [comment]
Ping @CAMOBAP for help...

**Comment by CAMOBAP** [comment]
@Intelligent2013 you need to run `metanorma` via `bundle exec` like this:

`bundle exec metanorma site generate --agree-to-terms`

**Comment by Intelligent2013** [comment]
@CAMOBAP thank you! It's working now!
I'll continue the investigating.

**Comment by Intelligent2013** [comment]
@ronaldtse the issue with mn2pdf crashing due non-correct path to 'Source Han Sans Normal' font  fixed in v.1.30 https://github.com/metanorma/mn2pdf/releases/tag/v1.30

**Comment by ronaldtse** [comment]
So if we update mn2pdf gem it will work, right?

**Comment by Intelligent2013** [comment]
> So if we update mn2pdf gem it will work, right?

@ronaldtse yes.

**Comment by CAMOBAP** [comment]
@Intelligent2013 @ronaldtse we have automatic release flow, so if mn2pdf.jar released, mn2pdf-ruby will be released too

**Comment by ronaldtse** [comment]
Re-running jobs for new mn2pdf 1.3

**Pull request merged**
